### PR TITLE
fix: logs are never cleared

### LINKED ISSUE #247: [BUG]: logs are never cleared
**Describe the bug** 
logs are never cleared

**Expected behavior**
the logs should be cleared after an app restart

**Screenshots** 

**Versions (please complete the following information):**

- OS: Windows 11
- Captain v1.0.0-alpha.59

### PR DESCRIPTION
**Pull request by pixelass**
## Issues closed

closes #247

### CODE REVIEW

**Comment by pixelass** [comment]
related? 
https://github.com/winstonjs/winston-daily-rotate-file/issues/184

**Comment by pixelass** [comment]
look into: https://github.com/megahertz/electron-log#readme

**Review by TimPietrusky — APPROVED** [review]
LGTM!

**Pull request merged**
